version: '3.5'
# networking
# volumes
services:
  fx-vc-git-skill-bot:
    image: "apisecuriti/vc-git-skill-bot:2020-06-07-1826"
    #autodestroy: ALWAYS
    #autorestart: ON_FAILURE
    #autoredeploy: true
    #target_num_containers: 2
    #sequential_deployment: true
    #deployment_strategy: high_availability
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    environment:
      # RabbitMQ
      - FX_HOST=${RABBITMQ_HOST}
      - FX_PORT=${RABBITMQ_PORT}
      - FX_USERNAME=${RABBITMQ_DEFAULT_USER}
      - FX_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

  fx-it-fx-skill-bot:
    image: "apisecuriti/issue-tracker-fx-skill-bot:2020-06-07-1838"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    environment:
    # RabbitMQ
    - FX_HOST=${RABBITMQ_HOST}
    - FX_PORT=${RABBITMQ_PORT}
    - FX_USERNAME=${RABBITMQ_DEFAULT_USER}
    - FX_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

